name: website
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  audioplayers: ^3.0.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/
  fonts:
  - family: RubikIso
    fonts:
      - asset: assets/fonts/RubikIso-Regular.ttf
  - family: ShantellSans
    fonts:
      - asset: assets/fonts/ShantellSans-Regular.ttf
  - family: KleeOne
    fonts:
      - asset: assets/fonts/KleeOne-Regular.ttf
